import {loadJson,markActiveNav} from './app.js';
const rel = document.body.dataset.dataPrefix || './';
function impactPills(items=[]){return `<div class="impact-list">${items.map(i=>`<span>${i}</span>`).join('')}</div>`}
function riskList(items=[]){return `<ul class="list">${items.map(r=>`<li>${r}</li>`).join('')}</ul>`}
function renderLayer(layer){return `<article class="card"><span class="pill">SATF Layer</span><h3>${layer.name}</h3><p>${layer.plainEnglish}</p><p class="muted"><strong>Business purpose:</strong> ${layer.businessPurpose}</p><h4>Examples</h4>${riskList(layer.examples||[])}<h4>Business risks</h4>${riskList(layer.businessRisks)}</article>`}
function renderComponent(c){return `<article class="card component-card"><span class="pill">${c.tag||'Component'}</span><h3>${c.name}</h3><p>${c.whatItIs}</p><p class="muted"><strong>Why it matters:</strong> ${c.whyItMatters}</p><h4>Business value</h4>${riskList(c.businessValue||[])}<h4>Business impact</h4>${impactPills(c.businessImpact)}<h4>What could go wrong</h4>${riskList(c.whatCouldGoWrong)}</article>`}
function renderImpact(i){return `<article class="card"><span class="pill">Business outcome</span><h3>${i.name}</h3><p class="muted">${i.description}</p><h4>Typical questions</h4>${riskList(['What business process could be affected?','Who is accountable for the action?','What evidence would prove what happened?','Which controls reduce the blast radius?'])}</article>`}
async function init(){markActiveNav();let data;try{data=await loadJson(`${rel}data/business-guide.json`);}catch(err){console.warn('Business guide JSON not loaded; using static fallback content.',err);return;}const layerRoot=document.querySelector('#layers');const compRoot=document.querySelector('#components');const impactRoot=document.querySelector('#impacts');const search=document.querySelector('#guideSearch');if(layerRoot) layerRoot.innerHTML=data.layers.map(renderLayer).join('');if(impactRoot) impactRoot.innerHTML=data.impacts.map(renderImpact).join('');function draw(q=''){if(!compRoot)return;const term=q.toLowerCase();const list=data.components.filter(c=>`${c.name} ${c.tag} ${c.whatItIs} ${c.whatCouldGoWrong.join(' ')}`.toLowerCase().includes(term));compRoot.innerHTML=list.map(renderComponent).join('');}draw();search?.addEventListener('input',e=>draw(e.target.value));}
init();
